### PR TITLE
Add Feature to update formatting of cells not changing contents of cells

### PR DESCRIPTION
**Pull request by hegrecom**
Hi! I'm really happy to find this great gem.
But when I've used this gem, I'd felt that I'd wanted to update just some parameters of some cells keeping cells' contents and formatting already applied. 
Because, It was really hard to draw some tables like the following.
Screen Shot 2020-10-16 at 9 46 46 AM

I needed to create formats for every cells and codes became really verbose.
```
workbook = WriteXLSX.new('some.xlsx')
worksheet = workbook.add_worksheet

top_left__header_format = workbook.add_format(align: 'center', bold: 1, bg_color: 31, border: 1, top: 2, left: 2)
top_header_format = workbook.add_format(align: 'center', bold: 1, bg_color: 31, border: 1, top: 2)
top_right_header_format = workbook.add_format(align: 'center', bold: 1, bg_color: 31, border: 1, top: 2, right: 2)
top_left_body_format = workbook.add_format(align: 'center', border: 1, top: 2, left: 2)
top_body_format = workbook.add_format(align: 'center', border: 1, top: 2)
top_right_body_format = workbook.add_format(align: 'center', border: 1, top: 2, right: 2)
left_body_format = workbook.add_format(align: 'center', border: 1, left: 2)
body_format = workbook.add_format(align: 'center', border: 1)
right_body_format = workbook.add_format(align: 'center', border: 1, right: 2)
bottom_left_body_format = workbook.add_format(align: 'center', border: 1, bottom: 2, left: 2)
bottom_body_format = workbook.add_format(align: 'center', border: 1, bottom: 2)
bottom_right_body_format = workbook.add_format(align: 'center', border: 1, bottom: 2, right: 2)

worksheet.write(0, 0, 'Table', top_left_header_format)
worksheet.write(0, 1, 'Header', top_header_format)
worksheet.write(0, 2, 'Contents', top_right_header_format)
worksheet.write(1, 0, 'table', top_left_body_format)
worksheet.write(1, 1, 'body', top_body_format)
worksheet.write(1, 2, 'contents', top_right_body_format)
worksheet.write(2, 0, 'table', left_body_format)
worksheet.write(2, 1, 'body', body_format)
worksheet.write(2, 2, 'contents', right_body_format)
worksheet.write(3, 0, 'table', bottom_left_body_format)
worksheet.write(3, 1, 'body', bottom_body_format)
worksheet.write(3, 2, 'contents', bottom_right_body_format)
```
So, I thought It would be great if I can just update formatting of the specified cell and implemented the feature.
With methods I added above table could be drawn like this.
```
workbook = WriteXLSX.new('some.xlsx')
worksheet = workbook.add_worksheet

common_format = workbook.add_format(align: 'center', border: 1)

table_contents = [
  ['Table', 'Header', 'Contents'],
  ['table', 'body', contents'],
  ['table', 'body', contents'],
  ['table', 'body', contents']
]

worksheet.write_col(0, 0, table_contents, common_format)
worksheet.update_range_format_with_params(0, 0, 0, 2, bold: 1, top: 2, bottom: 2, bg_color: 31)
worksheet.update_range_format_with_params(0, 0, 3, 0, left: 2)
worksheet.update_range_format_with_params(0, 2, 3, 2, right: 2)
worksheet.update_range_format_with_params(3, 0, 3, 2, bottom: 2)
```

### CODE REVIEW

**Comment by hegrecom** [comment]
Need more test

**Comment by hegrecom** [comment]
CellData can share Format object. So, If I directly update format properties, cells that share the format object formatting can be also changed. Fixed this issue by always generating new format object.

**Comment by taehwakang** [comment]
@cxn03651 Please review this PR and give me feedbacks if you have any.

**Comment by cxn03651** [comment]
Hi,

Thank you for your great effort.
v0.85.11 has been released.

**Pull request merged**
