### PR TITLE
Append directive `frozen-string-literal` to files

### PR DESCRIPTION
**Pull request by ukolovda**
I also run tests with `--enable=frozen-string-literal` option:
```bash
$ RUBYOPT="--enable=frozen-string-literal" rake test
```
Test fails with `rubyzip` 2.3.2 (latest published version), but pass when I run it with last `master` version on Github.

@cxn03651 should we still support old Ruby version (2.0-2.4)? It installing is hard because old OpenSSL and other system libraries.

### CODE REVIEW

**Comment by cxn03651** [comment]
Thanks for the patch.

I also wanted to stop supporting too old versions of Ruby.
In fact, I only have Ruby 2.7.6 or later on my computer.

I'm planning to release write_xlsx v1.10.0 in February. This is the change that will follow the original perl library.
At that time, I will merge your patch, and change the version of Ruby that this library supports.

Which version would be appropriate to support?
Ruby 2.5 or later ? I'd be happy to hear your opinion.

**Comment by ukolovda** [comment]
I think Ruby from 2.5 and later will be fine. It supports string "dedup" operator (unary -) which reduce RAM consume.

**Comment by ukolovda** [comment]
@cxn03651  sorry, I forgot to remove my temporary comments in `test/helper.rb`. 
I restore it now and made amend commit and force-push.

**Comment by cxn03651** [comment]
Thank you for your suggestion.
Please wait for new release.

**Pull request merged**
